### ISSUE TITLE
出現錯誤

### ISSUE THREAD

**Issue by plok88** [ghnmqdtg/Taiwan_Memory_Parser#1]
出現錯誤 如下
File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Taiwan_Memory_Parser-master\resource_parser.py", line 92, in save_pictures
    open((f"./img/{self.title}/{filename}.jpg"), "wb").write(data.content)
FileNotFoundError: [Errno 2] No such file or directory: './img/\n\n                                                            
似乎無法建立img檔案夾
可否幫忙解決這問題謝謝

未來會加入自訂路徑，該功能實做很簡單，只是開發階段用不上所已沒有做
可否加入此功能

**Comment by ghnmqdtg** [comment]
Hi @plok88 

我已經修復好這個 issue 囉，麻煩你在 cmd 下 `git pull` 指令更新程式碼，如果有再遇到任何 bug 的話再幫我開 issue，謝謝。

**Comment by plok88** [comment]
非常謝謝，因為正在研究熱蘭遮城史料，許用到您的程式，謝謝，另不知您修復的壁畫內容為何？

ghnmqdtg ***@***.***> 於 2022年7月13日 週三 下午7:07 寫道：

**Comment by plok88** [comment]
thank you
修改後
目前程式BUG為程式有跑且顯示圖片抓取完成,但無實際下載物件到電腦中
電腦中找不到下載檔案及IMG資料夾
